name: 'LaTeX Build'
description: 'Greet someone and record the time'
inputs:
  build-files:
    description: A Line-separated list of paths of the TeX files to build.
    required: true
    default: 'main.tex'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.build-files }}
